[project]
name = "supervaizer"
description = "Controller system for Supervaize"
readme = "README.md"
requires-python = ">=3.12"
authors = [
    { name = "Alain Prasquier - Supervaize", email = "alain@supervaize.com" },
]
dependencies = [
    "art>=6.5",
    "cryptography>=44.0.2",
    "demjson3>=3.0.6",
    "deprecated>=1.2.18",
    "fastapi>=0.115.12",
    "httpx>=0.28.1",
    "loguru>=0.7.3",
    "orjson>=3.10.16",
    "pydantic>=2.11.3",
    "python-slugify>=8.0.4",
    "rich>=14.0.0",
    "shortuuid>=1.0.13",
    "typer>=0.9.0",
    "uvicorn>=0.34.0",
]
license = "MPL-2.0"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Mozilla Public License 2.0 (MPL 2.0)",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
]
dynamic = ["version"]

[project.scripts]
supervaizer = "supervaizer.cli:app"

[project.optional-dependencies]
dev = [
    "pytest>=8.3.5",
    "pytest-cov>=4.1.0",
    "pre-commit>=3.7.0",
    "respx>=0.22.0",
    "ruff>=0.3.4",
    "hatch>=1.9.3",
    "pytest-sugar>=1.0.0",
    "pytest-asyncio>=0.26.0",
    "pytest-mock>=3.14.0",
    "mypy>=1.15.0",
    "types-deprecated>=1.2.15.20250304",
    "jsonschema>=4.23.0",
    "pytest-mock>=3.14.0",
]

[tool.pytest.ini_options]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "db: calls to the database",
    "current: test under development",
]
addopts = "--cov=supervaizer --cov-report=term-missing --cov-report=html"
asyncio_default_fixture_loop_scope = "function"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool]
[tool.hatch]
[tool.hatch.version]
path = "supervaizer/__version__.py"

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]             # unused imports
"tests/*" = ["N802", "N803", "N806"] # test function naming

[tool.ruff.lint.isort]
combine-as-imports = true
force-wrap-aliases = true

[tool.commitizen]
name = "cz_gitmoji"

[tool.mypy]
python_version = "3.12"
strict = true
ignore_missing_imports = true
disallow_untyped_defs = true
warn_unused_ignores = false
no_implicit_optional = true
